<html>
<head>
    <link type="text/css" rel="stylesheet" href="/lib/jquery-ui-1.10.3.custom/css/ui-lightness/jquery-ui-1.10.3.custom.min.css" />
    <script type="text/javascript" language="JavaScript" src="/lib/jquery-ui-1.10.3.custom/js/jquery-1.9.1.min.js"></script>
    <script type="text/javascript" language="JavaScript" src="/lib/jquery-ui-1.10.3.custom/js/jquery-ui-1.10.3.custom.min.js"></script>
    <script type="text/javascript" language="JavaScript" src="/js/metroDatePicker.js"></script>
    <script type="text/javascript" language="JavaScript" src="/js/weatherapp.js"></script>
</head>
</html>
<body>
    <div id="date">
        <input type="text" id="datepicker" />
    </div>
</body>